# Generated by Django 5.0.10 on 2025-10-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, default='', help_text='Google Calendar event ID for syncing', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='bookings_bo_client__ca5b55_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['confirmation_code'], name='bookings_bo_confirm_783da7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
