# Generated by Django 5.0.10 on 2025-10-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='bookings_bo_client__ca5b55_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['confirmation_code'], name='bookings_bo_confirm_783da7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
