# Generated by Django 5.0.14 on 2026-02-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("services", "0002_booking_source_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("voucher", "Voucher"),
                    ("manual", "Manual"),
                ],
                default="online",
                help_text="How this booking originated",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="voucher_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Gift voucher code if booked via voucher redemption",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["source"], name="bookings_bo_source_54090c_idx"),
        ),
    ]
