# Generated by Django 5.0.14 on 2026-02-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_source_voucher_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("-created_at",)},
        ),
    ]
