# Generated by Django 5.0.14 on 2026-02-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
    ]
