# Generated by Django 5.0.14 on 2026-02-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactsubmission",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
            },
        ),
    ]
