# Generated by Django 5.0.10 on 2025-10-27 10:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title_en', models.CharField(blank=True, default='', help_text="Main headline - Keep it short and impactful (e.g., 'Find Your Balance')", max_length=200)),
                ('hero_title_fr', models.CharField(blank=True, default='', help_text="Titre principal - Court et percutant (ex: 'Trouvez Votre Équilibre')", max_length=200)),
                ('hero_subtitle_en', models.CharField(blank=True, default='', help_text='Tagline under the title - Describe what you offer in one sentence', max_length=300)),
                ('hero_subtitle_fr', models.CharField(blank=True, default='', help_text='Sous-titre - Décrivez votre offre en une phrase', max_length=300)),
                ('about_title_en', models.CharField(blank=True, default='', help_text="Section heading (e.g., 'About Me')", max_length=200)),
                ('about_title_fr', models.CharField(blank=True, default='', help_text="Titre de section (ex: 'À Propos de Moi')", max_length=200)),
                ('about_subtitle_en', models.CharField(blank=True, default='', help_text="Subtitle under About title (e.g., 'Dedicated to Your Wellness')", max_length=200)),
                ('about_subtitle_fr', models.CharField(blank=True, default='', help_text="Sous-titre (ex: 'Dédiée à Votre Bien-Être')", max_length=200)),
                ('about_intro_en', wagtail.fields.RichTextField(blank=True, default='', help_text='Your professional introduction - Who you are and your experience')),
                ('about_intro_fr', wagtail.fields.RichTextField(blank=True, default='', help_text='Votre présentation professionnelle - Qui vous êtes et votre expérience')),
                ('about_certification_en', models.CharField(blank=True, default='', help_text="Your main certification (e.g., 'Certified Professional Massage Therapist')", max_length=200)),
                ('about_certification_fr', models.CharField(blank=True, default='', help_text="Votre certification principale (ex: 'Massothérapeute Professionnelle Certifiée')", max_length=200)),
                ('about_approach_title_en', models.CharField(blank=True, default='', help_text="Title for your approach section (e.g., 'My Approach')", max_length=200)),
                ('about_approach_title_fr', models.CharField(blank=True, default='', help_text="Titre de votre approche (ex: 'Mon Approche')", max_length=200)),
                ('about_approach_text_en', wagtail.fields.RichTextField(blank=True, default='', help_text='Describe your unique approach to massage therapy')),
                ('about_approach_text_fr', wagtail.fields.RichTextField(blank=True, default='', help_text='Décrivez votre approche unique du massage thérapeutique')),
                ('about_specialties_title_en', models.CharField(blank=True, default='', help_text="Title for specialties section (e.g., 'Specialties')", max_length=200)),
                ('about_specialties_title_fr', models.CharField(blank=True, default='', help_text="Titre des spécialités (ex: 'Spécialités')", max_length=200)),
                ('specialty_1_en', models.CharField(blank=True, default='', help_text="First specialty (e.g., 'Deep Tissue Therapy')", max_length=200)),
                ('specialty_1_fr', models.CharField(blank=True, default='', help_text="Première spécialité (ex: 'Thérapie Tissus Profonds')", max_length=200)),
                ('specialty_2_en', models.CharField(blank=True, default='', help_text="Second specialty (e.g., 'Swedish Relaxation')", max_length=200)),
                ('specialty_2_fr', models.CharField(blank=True, default='', help_text="Deuxième spécialité (ex: 'Relaxation Suédoise')", max_length=200)),
                ('specialty_3_en', models.CharField(blank=True, default='', help_text="Third specialty (e.g., 'Sports Recovery')", max_length=200)),
                ('specialty_3_fr', models.CharField(blank=True, default='', help_text="Troisième spécialité (ex: 'Récupération Sportive')", max_length=200)),
                ('specialty_4_en', models.CharField(blank=True, default='', help_text="Fourth specialty (e.g., 'Prenatal Care')", max_length=200)),
                ('specialty_4_fr', models.CharField(blank=True, default='', help_text="Quatrième spécialité (ex: 'Soins Prénatals')", max_length=200)),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number with country code (e.g., +33 6 00 00 00 00)', max_length=64)),
                ('email', models.EmailField(blank=True, default='', help_text='Professional email address for bookings and inquiries', max_length=254)),
                ('address_en', models.CharField(blank=True, default='', help_text="Your business address in English (e.g., 'Paris, France' or full address)", max_length=300)),
                ('address_fr', models.CharField(blank=True, default='', help_text="Votre adresse professionnelle en français (ex: 'Paris, France' ou adresse complète)", max_length=300)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Background image for hero section - Choose a calming, professional spa photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_fr', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_fr', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='cms.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SerenitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Serenity', help_text='Site brand name', max_length=100)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('business_hours', models.CharField(blank=True, default='Mon-Sat: 9:00-19:00', help_text='Display hours on site', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
