# Generated by Django 5.0.10 on 2025-10-17 19:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('hero_title_fr', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subtitle_en', models.CharField(blank=True, default='', max_length=300)),
                ('hero_subtitle_fr', models.CharField(blank=True, default='', max_length=300)),
                ('about_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('about_title_fr', models.CharField(blank=True, default='', max_length=200)),
                ('about_text_en', wagtail.fields.RichTextField(blank=True, default='')),
                ('about_text_fr', wagtail.fields.RichTextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_en', models.CharField(blank=True, default='', max_length=300)),
                ('address_fr', models.CharField(blank=True, default='', max_length=300)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SerenitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Serenity', help_text='Site brand name', max_length=100)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('business_hours', models.CharField(blank=True, default='Mon-Sat: 9:00-19:00', help_text='Display hours on site', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
