# Generated by Django 5.0.14 on 2026-02-18 12:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Check this to show the Gift Voucher floating icon on the site.",
                    ),
                ),
                (
                    "modal_title_en",
                    models.CharField(
                        default="Give the Gift of Relaxation", max_length=100
                    ),
                ),
                (
                    "modal_title_fr",
                    models.CharField(
                        default="Offrez le Cadeau de la Détente", max_length=100
                    ),
                ),
                (
                    "modal_text_en",
                    models.TextField(
                        default="Fill out the details below to send a massage voucher."
                    ),
                ),
                (
                    "modal_text_fr",
                    models.TextField(
                        default="Remplissez les détails ci-dessous pour envoyer un bon cadeau."
                    ),
                ),
                (
                    "email_subject_en",
                    models.CharField(default="You've received a gift!", max_length=255),
                ),
                (
                    "email_subject_fr",
                    models.CharField(
                        default="Vous avez reçu un cadeau !", max_length=255
                    ),
                ),
                (
                    "email_heading_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: heading shown inside the voucher email (English).",
                        max_length=120,
                    ),
                ),
                (
                    "email_heading_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : titre dans l'email bon cadeau (Français).",
                        max_length=120,
                    ),
                ),
                (
                    "email_intro_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: intro sentence for recipient email (English). Use {purchaser_name}.",
                        max_length=255,
                    ),
                ),
                (
                    "email_intro_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : phrase d'intro (Français). Utilisez {purchaser_name}.",
                        max_length=255,
                    ),
                ),
                (
                    "email_redeem_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: redemption instructions (English). Use {site_name}.",
                        max_length=255,
                    ),
                ),
                (
                    "email_redeem_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : instructions (Français). Utilisez {site_name}.",
                        max_length=255,
                    ),
                ),
                (
                    "email_closing_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: closing line (English).",
                        max_length=255,
                    ),
                ),
                (
                    "email_closing_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : phrase de fin (Français).",
                        max_length=255,
                    ),
                ),
                (
                    "form_message_placeholder_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override the message placeholder (English).",
                        max_length=255,
                    ),
                ),
                (
                    "form_message_placeholder_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : texte du message personnalisé (Français).",
                        max_length=255,
                    ),
                ),
                (
                    "form_submit_label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override the submit button label (English).",
                        max_length=100,
                    ),
                ),
                (
                    "form_submit_label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : texte du bouton d'envoi (Français).",
                        max_length=100,
                    ),
                ),
                (
                    "form_sending_label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override the loading label (English).",
                        max_length=100,
                    ),
                ),
                (
                    "form_sending_label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : texte du bouton en cours d'envoi (Français).",
                        max_length=100,
                    ),
                ),
                (
                    "form_success_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override success title shown after sending (English).",
                        max_length=150,
                    ),
                ),
                (
                    "form_success_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : titre de succès après l'envoi (Français).",
                        max_length=150,
                    ),
                ),
                (
                    "form_success_message_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override success message body (English).",
                        max_length=255,
                    ),
                ),
                (
                    "form_success_message_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : texte de succès (Français).",
                        max_length=255,
                    ),
                ),
                (
                    "form_code_label_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional: override 'Voucher Code' label (English).",
                        max_length=100,
                    ),
                ),
                (
                    "form_code_label_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optionnel : libellé pour 'Code du bon' (Français).",
                        max_length=100,
                    ),
                ),
                (
                    "floating_icon",
                    models.ForeignKey(
                        blank=True,
                        help_text="The small floating button icon (e.g. gift box, heart). Best size: around 150x150px WebP/PNG.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "voucher_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The decorative image inside the email sent to the recipient.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Voucher Settings",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Main headline - Keep it short and impactful (e.g., 'Find Your Balance')",
                        max_length=200,
                    ),
                ),
                (
                    "hero_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre principal - Court et percutant (ex: 'Trouvez Votre Équilibre')",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tagline under the title - Describe what you offer in one sentence",
                        max_length=300,
                    ),
                ),
                (
                    "hero_subtitle_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sous-titre - Décrivez votre offre en une phrase",
                        max_length=300,
                    ),
                ),
                (
                    "about_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Section heading (e.g., 'About Me')",
                        max_length=200,
                    ),
                ),
                (
                    "about_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre de section (ex: 'À Propos de Moi')",
                        max_length=200,
                    ),
                ),
                (
                    "about_subtitle_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtitle under About title (e.g., 'Dedicated to Your Wellness')",
                        max_length=200,
                    ),
                ),
                (
                    "about_subtitle_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sous-titre (ex: 'Dédiée à Votre Bien-Être')",
                        max_length=200,
                    ),
                ),
                (
                    "about_intro_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Your professional introduction - Who you are and your experience",
                    ),
                ),
                (
                    "about_intro_fr",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Votre présentation professionnelle - Qui vous êtes et votre expérience",
                    ),
                ),
                (
                    "about_certification_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Your main certification (e.g., 'Certified Professional Massage Therapist')",
                        max_length=200,
                    ),
                ),
                (
                    "about_certification_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Votre certification principale (ex: 'Massothérapeute Professionnelle Certifiée')",
                        max_length=200,
                    ),
                ),
                (
                    "about_approach_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title for your approach section (e.g., 'My Approach')",
                        max_length=200,
                    ),
                ),
                (
                    "about_approach_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre de votre approche (ex: 'Mon Approche')",
                        max_length=200,
                    ),
                ),
                (
                    "about_approach_text_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Describe your unique approach to massage therapy",
                    ),
                ),
                (
                    "about_approach_text_fr",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Décrivez votre approche unique du massage thérapeutique",
                    ),
                ),
                (
                    "about_specialties_title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title for specialties section (e.g., 'Specialties')",
                        max_length=200,
                    ),
                ),
                (
                    "about_specialties_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titre des spécialités (ex: 'Spécialités')",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_video_public_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloudinary public ID for background video (e.g. 'serenity/corporate-loop'). Do NOT include extension.",
                        max_length=255,
                    ),
                ),
                (
                    "services_hero_video_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4 background video for the corporate hero section. This is stored on Cloudinary.",
                        null=True,
                        upload_to="services/videos/",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone number with country code (e.g., +33 6 00 00 00 00)",
                        max_length=64,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Professional email address for bookings and inquiries",
                        max_length=254,
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Your business address in English (e.g., 'Paris, France' or full address)",
                        max_length=300,
                    ),
                ),
                (
                    "address_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Votre adresse professionnelle en français (ex: 'Paris, France' ou adresse complète)",
                        max_length=300,
                    ),
                ),
                (
                    "services_hero_title_en",
                    models.CharField(
                        blank=True,
                        default="Corporate Wellness Programs",
                        help_text="Main title for the services hero section (English)",
                        max_length=255,
                    ),
                ),
                (
                    "services_hero_title_fr",
                    models.CharField(
                        blank=True,
                        default="Programmes de Bien-être en Entreprise",
                        help_text="Main title for the services hero section (Français)",
                        max_length=255,
                    ),
                ),
                (
                    "services_hero_price_en",
                    models.CharField(
                        blank=True,
                        default="€45/person",
                        help_text="Displayed price (English)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_price_fr",
                    models.CharField(
                        blank=True,
                        default="45€/personne",
                        help_text="Displayed price (Français)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_pricing_label_en",
                    models.CharField(
                        blank=True,
                        default="Starting from",
                        help_text="Label before price (English)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_pricing_label_fr",
                    models.CharField(
                        blank=True,
                        default="À partir de",
                        help_text="Label before price (Français)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_cta_en",
                    models.CharField(
                        blank=True,
                        default="Request a Quote",
                        help_text="CTA button text (English)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_cta_fr",
                    models.CharField(
                        blank=True,
                        default="Demander un Devis",
                        help_text="CTA button text (Français)",
                        max_length=100,
                    ),
                ),
                (
                    "services_hero_benefit_1_en",
                    models.CharField(
                        blank=True,
                        default="Professional equipment provided",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_benefit_1_fr",
                    models.CharField(
                        blank=True,
                        default="Équipement professionnel fourni",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_benefit_2_en",
                    models.CharField(
                        blank=True,
                        default="Flexible group sizes available",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_benefit_2_fr",
                    models.CharField(
                        blank=True,
                        default="Groupes flexibles disponibles",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_benefit_3_en",
                    models.CharField(
                        blank=True,
                        default="Boost team wellness and morale",
                        max_length=200,
                    ),
                ),
                (
                    "services_hero_benefit_3_fr",
                    models.CharField(
                        blank=True,
                        default="Améliorez le bien-être et le moral de l'équipe",
                        max_length=200,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Background image for hero section - Choose a calming, professional spa photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "services_hero_poster_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Poster image shown before / instead of video (background still).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title_en", models.CharField(blank=True, default="", max_length=200)),
                ("title_fr", models.CharField(blank=True, default="", max_length=200)),
                (
                    "subtitle_en",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "subtitle_fr",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_slides",
                        to="cms.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SerenitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="Serenity", help_text="Site brand name", max_length=100
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "business_hours",
                    models.CharField(
                        blank=True,
                        default="Mon-Sat: 9:00-19:00",
                        help_text="Display hours on site",
                        max_length=200,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title_en", models.CharField(blank=True, default="", max_length=200)),
                ("title_fr", models.CharField(blank=True, default="", max_length=200)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="cms.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
