# Generated by Django 5.0.10 on 2025-10-20 12:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_text_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_text_fr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_approach_text_en',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_approach_text_fr',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_approach_title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_approach_title_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_certification_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_certification_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_intro_en',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_intro_fr',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_specialties_title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_specialties_title_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_1_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_1_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_2_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_2_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_3_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_3_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_4_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_4_fr',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
