# Generated by Django 5.0.14 on 2026-02-23 15:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="address_en",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="address_fr",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="phone",
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="floating_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="The small floating button icon (e.g. gift box, heart). Best size: around 150×150 px WebP/PNG.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_approach_text_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Describe your unique approach to massage therapy.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_approach_text_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Décrivez votre approche unique du massage thérapeutique.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_approach_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title for your approach section (e.g. 'My Approach').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_approach_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre de votre approche (ex : 'Mon Approche').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_certification_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your main certification (e.g. 'Certified Professional Massage Therapist').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_certification_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Votre certification principale (ex : 'Massothérapeute Professionnelle Certifiée').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_intro_en",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Your professional introduction — who you are and your experience.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_intro_fr",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="Votre présentation professionnelle — qui vous êtes et votre expérience.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_specialties_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title for specialties section (e.g. 'Specialties').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_specialties_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre des spécialités (ex : 'Spécialités').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_subtitle_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subtitle under About title (e.g. 'Dedicated to Your Wellness').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_subtitle_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sous-titre (ex : 'Dédiée à Votre Bien-Être').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Section heading (e.g. 'About Me').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre de section (ex : 'À Propos de Moi').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image for hero section — choose a calming, professional spa photo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tagline under the title — describe your offer in one sentence.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sous-titre — décrivez votre offre en une phrase.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Main headline — keep it short and impactful (e.g. 'Find Your Balance').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre principal — court et percutant (ex : 'Trouvez Votre Équilibre').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_cta_en",
            field=models.CharField(
                blank=True,
                default="Request a Quote",
                help_text="CTA button text (English).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_cta_fr",
            field=models.CharField(
                blank=True,
                default="Demander un Devis",
                help_text="CTA button text (Français).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_poster_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Poster image shown before/instead of video.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_price_en",
            field=models.CharField(
                blank=True,
                default="€45/person",
                help_text="Displayed price (English).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_price_fr",
            field=models.CharField(
                blank=True,
                default="45€/personne",
                help_text="Displayed price (Français).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_pricing_label_en",
            field=models.CharField(
                blank=True,
                default="Starting from",
                help_text="Label before price (English).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_pricing_label_fr",
            field=models.CharField(
                blank=True,
                default="À partir de",
                help_text="Label before price (Français).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_title_en",
            field=models.CharField(
                blank=True,
                default="Corporate Wellness Programs",
                help_text="Main title for the services hero section (English).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_title_fr",
            field=models.CharField(
                blank=True,
                default="Programmes de Bien-être en Entreprise",
                help_text="Main title for the services hero section (Français).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4 background video for the corporate hero section. Stored on Cloudinary.",
                null=True,
                upload_to="services/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_hero_video_public_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloudinary public ID for background video (e.g. 'serenity/corporate-loop'). Do NOT include file extension.",
                max_length=255,
            ),
        ),
    ]
