# Generated by Django 5.0.14 on 2026-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serenitysettings",
            name="address_full",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full street address displayed on the site",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="serenitysettings",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Public contact email address",
                max_length=254,
            ),
        ),
    ]
