# Generated by Django 5.0.10 on 2025-10-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_1_en',
            field=models.CharField(blank=True, default='Professional equipment provided', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_1_fr',
            field=models.CharField(blank=True, default='Équipement professionnel fourni', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_2_en',
            field=models.CharField(blank=True, default='Flexible group sizes available', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_2_fr',
            field=models.CharField(blank=True, default='Groupes flexibles disponibles', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_3_en',
            field=models.CharField(blank=True, default='Boost team wellness and morale', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_benefit_3_fr',
            field=models.CharField(blank=True, default="Améliorez le bien-être et le moral de l'équipe", max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_cta_en',
            field=models.CharField(blank=True, default='Request a Quote', help_text='CTA button text (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_cta_fr',
            field=models.CharField(blank=True, default='Demander un Devis', help_text='CTA button text (Français)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_price_en',
            field=models.CharField(blank=True, default='€45/person', help_text='Displayed price (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_price_fr',
            field=models.CharField(blank=True, default='45€/personne', help_text='Displayed price (Français)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_pricing_label_en',
            field=models.CharField(blank=True, default='Starting from', help_text='Label before price (English)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_pricing_label_fr',
            field=models.CharField(blank=True, default='À partir de', help_text='Label before price (Français)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_title_en',
            field=models.CharField(blank=True, default='Corporate Wellness Programs', help_text='Main title for the services hero section (English)', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_title_fr',
            field=models.CharField(blank=True, default='Programmes de Bien-être en Entreprise', help_text='Main title for the services hero section (Français)', max_length=255),
        ),
    ]
