# Generated by Django 5.0.10 on 2025-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepage_services_hero_benefit_1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='specialty_5_en',
            field=models.CharField(blank=True, default='', help_text="Fifth specialty (e.g., 'Reflexology')", max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialty_5_fr',
            field=models.CharField(blank=True, default='', help_text="Cinquième spécialité (ex: 'Réflexologie')", max_length=200),
        ),
    ]
