# Generated by Django 5.0.10 on 2025-10-20 13:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_homepage_about_text_en_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_approach_text_en',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Describe your unique approach to massage therapy'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_approach_text_fr',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Décrivez votre approche unique du massage thérapeutique'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_approach_title_en',
            field=models.CharField(blank=True, default='', help_text="Title for your approach section (e.g., 'My Approach')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_approach_title_fr',
            field=models.CharField(blank=True, default='', help_text="Titre de votre approche (ex: 'Mon Approche')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_certification_en',
            field=models.CharField(blank=True, default='', help_text="Your main certification (e.g., 'Certified Professional Massage Therapist')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_certification_fr',
            field=models.CharField(blank=True, default='', help_text="Votre certification principale (ex: 'Massothérapeute Professionnelle Certifiée')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_intro_en',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Your professional introduction - Who you are and your experience'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_intro_fr',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Votre présentation professionnelle - Qui vous êtes et votre expérience'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_specialties_title_en',
            field=models.CharField(blank=True, default='', help_text="Title for specialties section (e.g., 'Specialties')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_specialties_title_fr',
            field=models.CharField(blank=True, default='', help_text="Titre des spécialités (ex: 'Spécialités')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_subtitle_en',
            field=models.CharField(blank=True, default='', help_text="Subtitle under About title (e.g., 'Dedicated to Your Wellness')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_subtitle_fr',
            field=models.CharField(blank=True, default='', help_text="Sous-titre (ex: 'Dédiée à Votre Bien-Être')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_en',
            field=models.CharField(blank=True, default='', help_text="Section heading (e.g., 'About Me')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_fr',
            field=models.CharField(blank=True, default='', help_text="Titre de section (ex: 'À Propos de Moi')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address_en',
            field=models.CharField(blank=True, default='', help_text="Your business address in English (e.g., 'Paris, France' or full address)", max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='address_fr',
            field=models.CharField(blank=True, default='', help_text="Votre adresse professionnelle en français (ex: 'Paris, France' ou adresse complète)", max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Professional email address for bookings and inquiries', max_length=254),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section - Choose a calming, professional spa photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, default='', help_text='Tagline under the title - Describe what you offer in one sentence', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle_fr',
            field=models.CharField(blank=True, default='', help_text='Sous-titre - Décrivez votre offre en une phrase', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, default='', help_text="Main headline - Keep it short and impactful (e.g., 'Find Your Balance')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_fr',
            field=models.CharField(blank=True, default='', help_text="Titre principal - Court et percutant (ex: 'Trouvez Votre Équilibre')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number with country code (e.g., +33 6 00 00 00 00)', max_length=64),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_1_en',
            field=models.CharField(blank=True, default='', help_text="First specialty (e.g., 'Deep Tissue Therapy')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_1_fr',
            field=models.CharField(blank=True, default='', help_text="Première spécialité (ex: 'Thérapie Tissus Profonds')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_2_en',
            field=models.CharField(blank=True, default='', help_text="Second specialty (e.g., 'Swedish Relaxation')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_2_fr',
            field=models.CharField(blank=True, default='', help_text="Deuxième spécialité (ex: 'Relaxation Suédoise')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_3_en',
            field=models.CharField(blank=True, default='', help_text="Third specialty (e.g., 'Sports Recovery')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_3_fr',
            field=models.CharField(blank=True, default='', help_text="Troisième spécialité (ex: 'Récupération Sportive')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_4_en',
            field=models.CharField(blank=True, default='', help_text="Fourth specialty (e.g., 'Prenatal Care')", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='specialty_4_fr',
            field=models.CharField(blank=True, default='', help_text="Quatrième spécialité (ex: 'Soins Prénatals')", max_length=200),
        ),
    ]
