# Generated by Django 5.0.14 on 2026-03-03 11:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_remove_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="faq_a1_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a1_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a2_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a2_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a3_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a3_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a4_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a4_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a5_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a5_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a6_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a6_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a7_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a7_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a8_en",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_a8_fr",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q1_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q1_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q2_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q2_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q3_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q3_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q4_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q4_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q5_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q5_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q6_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q6_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q7_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q7_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q8_en",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_q8_fr",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_subtitle_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short subtitle under the FAQ heading (English).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_subtitle_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sous-titre de la section FAQ (Français).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="FAQ section heading (English).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faq_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Titre de la section FAQ (Français).",
                max_length=200,
            ),
        ),
    ]
