# Generated by Django 5.0.10 on 2025-11-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_specialty'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_hero_poster_image',
            field=models.ForeignKey(blank=True, help_text='Poster image shown before / instead of video (background still).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_hero_video_public_id',
            field=models.CharField(blank=True, default='', help_text="Cloudinary public ID for background video (e.g. 'serenity/corporate-loop'). Do NOT include extension.", max_length=255),
        ),
    ]
