# Generated by Django 5.2.15 on 2026-07-02 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_homepage_faq_a1_en_homepage_faq_a1_fr_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterField(
            model_name='giftsettings',
            name='floating_icon',
            field=models.ForeignKey(blank=True, help_text='The small floating button icon (e.g. gift box, heart). ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
