# Generated by Django 5.0.10 on 2025-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_homepage_services_hero_poster_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_1_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_1_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_2_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_2_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_3_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_3_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_4_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_4_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_5_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='specialty_5_fr',
        ),
    ]
