# Generated by Django 5.0.10 on 2025-11-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_homepage_specialty_1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_hero_video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 background video for the corporate hero section. This is stored on Cloudinary.', null=True, upload_to='services/videos/'),
        ),
    ]
