# Generated by Django 5.0.10 on 2025-12-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_homepage_services_hero_video_file"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Check this to show the Gift Voucher floating icon on the site.",
                    ),
                ),
                (
                    "modal_title_en",
                    models.CharField(
                        default="Give the Gift of Relaxation", max_length=100
                    ),
                ),
                (
                    "modal_title_fr",
                    models.CharField(
                        default="Offrez le Cadeau de la Détente", max_length=100
                    ),
                ),
                (
                    "modal_text_en",
                    models.TextField(
                        default="Fill out the details below to send a massage voucher."
                    ),
                ),
                (
                    "modal_text_fr",
                    models.TextField(
                        default="Remplissez les détails ci-dessous pour envoyer un bon cadeau."
                    ),
                ),
                (
                    "email_subject_en",
                    models.CharField(default="You've received a gift!", max_length=255),
                ),
                (
                    "email_subject_fr",
                    models.CharField(
                        default="Vous avez reçu un cadeau !", max_length=255
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "voucher_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The decorative image that appears at the top of the email sent to the recipient.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Voucher Settings",
            },
        ),
    ]
