# Generated by Django 5.0.10 on 2025-12-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_giftsettings"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftsettings",
            name="floating_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="The small floating button icon (e.g. gift box, heart). Best size: around 150x150px WebP/PNG.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="voucher_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The decorative image inside the email sent to the recipient.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
