# Generated by Django 5.0.10 on 2025-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_giftsettings_floating_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftsettings",
            name="form_code_label_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override 'Voucher Code' label (English).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_code_label_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : libellé pour 'Code du bon' (Français).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_message_placeholder_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override the message placeholder (English).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_message_placeholder_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte du message personnalisé (Français).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_sending_label_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override the loading label (English).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_sending_label_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte du bouton en cours d’envoi (Français).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_submit_label_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override the submit button label (English).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_submit_label_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte du bouton d’envoi (Français).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_success_message_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override success message body (English).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_success_message_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte de succès (Français).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_success_title_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: override success title shown after sending (English).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="form_success_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : titre de succès après l’envoi (Français).",
                max_length=150,
            ),
        ),
    ]
