# Generated by Django 5.0.10 on 2026-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_giftsettings_form_code_label_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftsettings",
            name="email_closing_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: closing line (English).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_closing_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : phrase de fin (Français).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_heading_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: heading shown inside the voucher email (English).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_heading_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : titre dans l’email bon cadeau (Français).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_intro_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: intro sentence for recipient email (English). Use {purchaser_name}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_intro_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : phrase d’intro (Français). Utilisez {purchaser_name}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_redeem_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: redemption instructions (English). Use {site_name}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="giftsettings",
            name="email_redeem_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : instructions (Français). Utilisez {site_name}.",
                max_length=255,
            ),
        ),
    ]
