# Generated by Django 5.0.10 on 2026-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_giftsettings_email_closing_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftsettings",
            name="email_heading_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : titre dans l'email bon cadeau (Français).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="email_intro_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : phrase d'intro (Français). Utilisez {purchaser_name}.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="form_sending_label_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte du bouton en cours d'envoi (Français).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="form_submit_label_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : texte du bouton d'envoi (Français).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="giftsettings",
            name="form_success_title_fr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optionnel : titre de succès après l'envoi (Français).",
                max_length=150,
            ),
        ),
    ]
