# Generated by Django 5.0.10 on 2025-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiftVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                (
                    "purchaser_name",
                    models.CharField(max_length=128, verbose_name="Purchaser Name"),
                ),
                (
                    "purchaser_email",
                    models.EmailField(max_length=254, verbose_name="Purchaser Email"),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=128, verbose_name="Recipient Name"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Recipient Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Preferred Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_redeemed",
                    models.BooleanField(default=False, verbose_name="Redeemed"),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Redeemed At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Voucher",
                "verbose_name_plural": "Gift Vouchers",
                "ordering": ["-created_at"],
            },
        ),
    ]
