# Generated by Django 5.0.14 on 2026-02-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("recipient_name", models.CharField(max_length=200)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("sender_name", models.CharField(max_length=200)),
                ("sender_email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_redeemed", models.BooleanField(default=False)),
                ("preferred_language", models.CharField(default="fr", max_length=2)),
                (
                    "booking_confirmation",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("voucher", "Voucher"), ("manual", "Manual")],
                        default="voucher",
                        max_length=20,
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(max_length=254)),
                ("client_phone", models.CharField(max_length=64)),
                ("client_notes", models.TextField(blank=True, default="")),
                ("preferred_language", models.CharField(default="fr", max_length=2)),
                ("confirmation_code", models.CharField(max_length=12, unique=True)),
                (
                    "voucher_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "google_calendar_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["client_email"], name="vouchers_bo_client__7a22ae_idx"
                    ),
                    models.Index(
                        fields=["confirmation_code"],
                        name="vouchers_bo_confirm_888f5d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="vouchers_bo_status_c06b1c_idx"
                    ),
                    models.Index(
                        fields=["source"], name="vouchers_bo_source_e13aa7_idx"
                    ),
                ],
            },
        ),
    ]
