# Generated by Django 5.0.14 on 2026-02-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftvoucher",
            name="booking_confirmation",
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="calendar_event_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="calendar_event_link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="calendar_event_status",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_vouchers",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="giftvoucher",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
