# Generated by Django 5.0.14 on 2026-02-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftvoucher",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Gift Voucher",
                "verbose_name_plural": "Gift Vouchers",
            },
        ),
    ]
