# Generated by Django 5.0.14 on 2026-02-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonialreply",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
            },
        ),
    ]
