# Generated by Django 5.0.10 on 2025-11-27 19:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonialreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialreply',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='testimonials.testimonial', verbose_name='Témoignage parent'),
        ),
    ]
