# Generated by Django 5.0.14 on 2026-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookevent',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripewebhookevent',
            name='stripe_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
