# Generated by Django 5.2.15 on 2026-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripewebhookevent_livemode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='kind',
            field=models.CharField(choices=[('gift', 'Gift voucher'), ('booking', 'Booking')], db_index=True, default='gift', max_length=20),
        ),
    ]
